# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbb917dac8e973ed0325cae0c4f7596e0902a014593a52b191d3ffa878e9b7079401dbed597a3d127822df357352fe4bb51800ac6d75b49dca3fecff4f66dc13

test:
  secret_key_base: 4524c250b55fafa40d6e348df9144faf4c866dcfb24702f94b0ced42549dc169678453b4e98f16fc0a1a66c6202620c293842075edca84bbdf6764db99998aa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: b94e01582f7afe87ab4b06dae8b37d2645d800eb1c32c36da9decbdf48c9743f8dc09412a9ccc3894b527d9942791f1930174608f3b3ce60251aeee379204677
